version: "3.7"

services:
  backend:
    image: backend:latest
    networks:
      - rede-local
    ports:
      - 3000:3000
    restart: always

  frontend:
    image: react:latest
    networks:
      - rede-local
    ports:
      - 3001:3000
    environment:
      REACT_APP_API_HOST: backend
      REACT_APP_API_PORT: 3000
    depends_on:
      - backend
    restart: always

  dguests_database:
    image: mysql:5
    restart: always
    environment:
      MYSQL_USER: mateusgambaro
      MYSQL_PASSWORD: 13122100
      MYSQL_DATABASE: dguests_database
